version: 2.1

executors:
  rust-nightly-executor:
    docker:
        - image: rustlang/rust:nightly
  rust-executor:
    docker:
        - image: rust:latest
        - image: circleci/mongo:latest


jobs:
  check-fmt:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: check formatting
          command: cargo fmt -- --check
  build-native:
    executor: rust-nightly-executor
    steps:
      - checkout
      - run:
          name: build bot-dofus-orchestrator
          command: cargo build
  tests:
    executor: rust-nightly-executor
    steps:
      - checkout
      - run:
          name: test bot-dofus-orchestrator
          command: cargo test -- --test-threads=1
          environment:
            MONGO_ADDR: localhost
            DB_NAME: bot-dofus-orchestrator
            MONGO_PORT: 27017
workflows:
  version: 2
  build:
    jobs:
      - check-fmt
      - build-native
      - tests